language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
install: pip install unittest2 httplib2 mock --use-mirrors
script: python test.py
notifications:
    email:
        - jturk@sunlightfoundation.com
