language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
install: pip install mock nose requests --use-mirrors --upgrade
script: nosetests
notifications:
    email:
        - jturk@sunlightfoundation.com
