language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
install: pip install httplib2 chardet mock nose --use-mirrors
script: nosetests
notifications:
    email:
        - jturk@sunlightfoundation.com
