language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
install:
    - pip install mock nose --use-mirrors
    - pip install . --use-mirrors
script: nosetests
notifications:
    email:
        - jturk@sunlightfoundation.com
